import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgSelectModule } from '@ng-select/ng-select';
import { CommonModule } from '@angular/common';

interface ApprovalCard {
  id: string;
  count: number;
  title: string;
  role: string;
  chain: string;
  columns: string[];
}

@Component({
  selector: 'app-approval-master',
  standalone: true,
  imports: [CommonModule, FormsModule, NgSelectModule],
  templateUrl: './approval-master.component.html',
  styleUrl: './approval-master.component.scss'
})
export class ApprovalMasterComponent {
  approvalCards: ApprovalCard[] = [
    { 
      id: 'freight',
      count: 0, 
      title: 'Pending for Freight Bill Cancellation', 
      role: 'Approver 2 of 2',
      chain: "Meena Iyer (Approver 1) ➝ Rajesh Kumar (Approver 2)",
      columns: ['BILL NO', 'BILL DATE', 'CUSTOMER NAME', 'BILL AMOUNT', 'GENERATED BY', 'GENERATED DATE', 'TICKET ID', 'STATUS', 'ACTION']
    },
    { 
      id: 'vendor',
      count: 0, 
      title: 'Pending for Vendor Bill Cancellation', 
      role: 'Approver 2 of 2',
      chain: "Arun Shetty (Approver 1) ➝ Rajesh Kumar (Approver 2)",
      columns: ['BILL NO', 'BILL DATE', 'VENDOR NAME', 'BILL AMOUNT', 'GENERATED BY', 'GENERATED DATE', 'TICKET ID', 'STATUS', 'ACTION']
    },
    { 
      id: 'credit',
      count: 0, 
      title: 'Pending for Credit Note Generation', 
      role: 'Approver 2 of 2',
      chain: "Meena Iyer (Approver 1) ➝ Rajesh Kumar (Approver 2)",
      columns: ['CN REF NO', 'BILL NO', 'BILL DATE', 'CUSTOMER NAME', 'BILL AMOUNT', 'GENERATED BY', 'GENERATED DATE', 'TICKET ID', 'STATUS', 'ACTION']
    },
    { 
      id: 'thc',
      count: 0, 
      title: 'Pending for THC Approval', 
      role: 'Approver 2 of 2',
      chain: "Sunil Patil (Approver 1) ➝ Rajesh Kumar (Approver 2)",
      columns: ['THC NO', 'BILL DATE', 'VENDOR NAME', 'BILL AMOUNT', 'GENERATED BY', 'GENERATED DATE', 'TICKET ID', 'STATUS', 'ACTION']
    }
  ];

  selectedCard: ApprovalCard | null = null;

  selectCard(card: ApprovalCard) {
    this.selectedCard = card;
  }

  backToDashboard() {
    this.selectedCard = null;
  }
}
