import { Component } from '@angular/core';
import { DocketService } from '../../shared/services/docket.service';
import { BasicDetailService } from '../../shared/services/basic-detail.service';
import Swal from 'sweetalert2';
import { json } from 'stream/consumers';
import { formatDate } from '@angular/common';
@Component({
  selector: 'app-docket-list',
  standalone: false,
  templateUrl: './docket-list.component.html',
  styleUrl: './docket-list.component.scss'
})
export class DocketListComponent {
  constructor(
    public docketService: DocketService, private basicDetailService: BasicDetailService
  ) { }

  // onSubmit(){

  // }

  createPayload() {
    const listCCH = this.docketService.freightchargingData.map(charge => ({
      chargeCode: charge.chargeCode,
      chargeName: charge.chargeName,
      operator: charge.operator,
      chargeAmount: this.docketService.freightForm.get(charge.chargeCode)?.value || 0
    }));


    const invoiceList = this.docketService.invoiceRows.value.map((row: any, index: number) => {
      const obj: any = {
        srNo: row.srNo,
        dockno: this.docketService.basicDetailForm.value.cNoteNo,
        invno: row.invoiceNo || '',
        invdt: row.invoicedate || null,
        declval: row.declaredvalue || 0,
        pkgsno: row.noOfPkgs || 0,
        actuwt: row.actualWeight || 0,
        voL_L: row.length || 0,
        voL_B: row.breadth || 0,
        voL_H: row.height || 0,
        toT_CFT: row.cubicweight || 0,
        vol_cft: row.cubicweight || 0,
        part_No: '',
        eWayBillNo: row.ewayBillNo || '',
        eWayInvoicevalue: 0,
        eWayBillInvoiceDate: row.ewayinvoiceDate || null,
        chrgwt: 0
      };

      // ✅ conditionally add eWayBillExpiredDate only if eWayBillNo has value
      if (row.ewayBillNo) {
        obj.eWayBillExpiredDate = row.ewayBillExpiry || null;
      }

      return obj;
    });
    debugger
    const payload = {
      dvm: {
        listCCH: listCCH
      },
      // wmd: {
        "wmd": {
          "dockno": this.docketService.basicDetailForm.value.cNoteNo,
          "docksf": ".",
  //         "dockdt": this.docketService.basicDetailForm.value.cNoteDate
  // ? new Date(this.docketService.basicDetailForm.value.cNoteDate).toISOString()
  // : null,
          "orgncd": this.docketService.basicDetailForm.value.origin,
          "destcd": this.docketService.basicDetailForm.value.destination,
          "reassigN_DESTCD": this.docketService.basicDetailForm.value.destination,
          "from_loc": this.docketService.basicDetailForm.value.fromCity,
          "to_loc": this.docketService.basicDetailForm.value.toCity,
          "dly_loc": "",
          // "cdeldt": this.docketService.freightData.edd,
          // "cdeldt": '2025-08-18T05:45:05.992Z',
          "paybas": this.docketService.basicDetailForm.value.billingType,
          "pkgsno": this.docketService.invoiceform.value.totalNoOfPkgs,
          "actuwt": this.docketService.invoiceform.value.finalActualWeight,
          "chrgwt": this.docketService.invoiceform.value.totalActualWeight,
          "chargedPkgsNo": this.docketService.invoiceform.value.chargeWeightPerPkg,
          "qty": 0,
          "prodcd": this.docketService.basicDetailForm.value.contents,
          "spl_svc_req": "",
          "stax_paidby": "",//dropdown mathi avshe teni key
          "stax_regno": "",
          "service_Class": this.docketService.basicDetailForm.value.serviceType,
          "ftl_types": this.docketService.basicDetailForm.value.typeMovement,
          "fincmplbr": this.docketService.freightForm.value.billedAt,
          "csgncd": '8888',
          "csgnnm": this.docketService.consignorForm.value.consignorName,
          "csgnaddr": this.docketService.consignorForm.value.consignorAddress,
          "csgnaddR1": "",
          "companyLogoUrl": "",
          "csgnCity": this.docketService.consignorForm.value.consignorCity,
          "csgnPinCode": this.docketService.consignorForm.value.consignorPincode,
          "csgnTeleNo": this.docketService.consignorForm.value.consignorMobile,
          "csgnEmail": this.docketService.consignorForm.value.consignorEmail,
          "csgecd": '8888',
          "csgenm": this.docketService.consignorForm.value.consigneeName,
          "csgeaddr": this.docketService.consignorForm.value.consigneeAddress,
          "csgeaddR1": "",
          "csgeCity": this.docketService.consignorForm.value.consigneeCity,
          "csgePinCode": this.docketService.consignorForm.value.consigneePincode,
          "csgeTeleNo": this.docketService.consignorForm.value.consigneeMobile,
          "csgeEmail": this.docketService.consignorForm.value.consigneeEmail,
          "partY_CODE": this.docketService.basicDetailForm.value.billingParty,
          "privatemark": this.docketService.consignorForm.value.privateMark,
          "tpnumber": this.docketService.consignorForm.value.tpNumber,
          "trN_MOD": this.docketService.basicDetailForm.value.mode,
          "coD_DOD": this.docketService.basicDetailForm.value.IsCODDOD,
          "cfT_YN": this.docketService.step2DetailsList.isVolumentric ==='Y'?true:false,
          "diplomat": "",
          "dacC_YN": this.docketService.basicDetailForm.value.isDACC,  // step2 na response ma pn
          "localCN_YN": this.docketService.basicDetailForm.value.isLocalNote, //y and n
          "part": "",
          "pickup_Dely": this.docketService.basicDetailForm.value.pickup,
          "ugc": "",
          "permit_yn": "",// api baki chhe
          "permit_recvd_at": "",
          // "permitdt": new Date().toISOString(),
          // "permitdt": '2025-08-18T05:45:05.992Z',
          "permit_recvd_dt": "",
          "permit_No": "",
          "permit_validity_dt": "",
          "dockdT_Entry": new Date().toISOString(),
          "entryby": "string", // je user login hoy tenu userId
          "lastEditDate": "",
          "lastEditBy": "",
          "tohub_dest_reassigndt": null,
          "pkgsty": this.docketService.basicDetailForm.value.packingType,
          "insuyn": this.docketService.consignorForm.value.riskType,  // jo Carrier's Risk hoy to c ,owener hoy to 'o'
          "insupl": this.docketService.consignorForm.value.policyNo,
          // "insupldt": this.docketService.consignorForm.value.policyDate || null,
          // "insupldt": '2025-08-18T05:45:05.992Z',
          "codno": "",
          "ctr_no": this.docketService.consignorForm.value.customerRefNo,
          "modvat_encl": '',
          "modvat_no": "",
          "tot_modvat":Number(this.docketService.consignorForm.value.internalCovers)||0,
          "tot_covers": Number(this.docketService.consignorForm.value.modvatCovers) || 0,
          "codchrg": this.docketService.step2DetailsList.codCharged,
          "codamt": this.docketService.step2DetailsList.codCharged,
          "businesstype": this.docketService.basicDetailForm.value.businessType,
          "loadtype": "",
          "entrysheetno": "",
          "obdno": "",
          "bacode": "", //controller side thi
          "dopino": "",
          "edited": "",
          "editinfo": "",
          "dkT_SRNO": 0,
          "stax_exmpt_yn": this.docketService.basicDetailForm.value.exemptServices ? 'N' : 'Y',
          "party_as": "",
          "sourcedockno": this.docketService.basicDetailForm.value.referenceDocket,
          "multiplepickup_yn": "",
          "multipledelivery_yn": "",
          "doctype": "DKT",
          "multidelivery_yn": "",
          "multipickup_yn": "",
          "ctr_gpno": "",
          "ctr_delno": "",
          "pl_partner": "",
          "oct_amt": 0,
          "csgnaddrcd": "",
          "csgeaddrcd": "",
          "manual_dockno": this.docketService.basicDetailForm.value.cNoteNo,
          "local_stax_regno": "",
          "pl_costid": "",
          "pl_costid_reason": "",
          "company_code": "C003", //login mathi
          "hday_appl_yn": "",
          "csgnmobile": this.docketService.consignorForm.value.consignorMobile,
          "csgemobile": this.docketService.consignorForm.value.consigneeMobile,
          "quot_no": "",
          "agnd_no": "",
          "party_name": this.docketService.basicDetailForm.value.billingName,
          "primary_Company_DockNO": "",
          "hday_booked_yn": "",
          "cutoff_applied_yn": "",
          "engineNo": "",
          "modelNo": "",
          "gpsNo": "",
          "csgnTinNo": "",
          "csgncstNo": "",
          "csgeTinNo": "",
          "csgecstNo": "",
          "tamNo": "",
          "chassisNo": "",
          "flagAdvanceReceived": "",
          "p03BillLoc": "",
          "industry": "",
          "vehicleNo": this.docketService.basicDetailForm.value.vehicleno,
          "employeR_PRINCIPAL": " ",
          "staX_REMOVE_REMARK": "",
          "docketMode": "F",
          "gcType": "",
          "internationalType1": "",
          "internationalType2": "",
          "domesticType": "",
          "isNewPortal": true,
          "pfqty": 0,
          "fbqty": 0,
          "isGenFromNew": "",
          "cfrno": "",
          "isDefenceGC": true,
          "updateComments": "",
          "isSafeEx": true,
          "cft": this.docketService.invoiceform.value.cftTotal,
          "dktGenerationType": 0,
          "surChgExcludefrom27dec14": true,
          "isAdditionalAmountAdd": true,
          "newSvcTaxRule1Apr15": true,
          "trnServiceType": "string",
          "isTSIncomeAccouting": true,
          "surChgRemoveOn7May2015": true,
          "isMVCPortal": true,
          "isDevidedBill": true,
          "manuallyPassAccouting07Aug15": true,
          "fbreceiveqty": 0,
          "pfreceiveqty": 0,
          "fbbalqty": 0,
          "pfbalqty": 0,
          "ledqty": 0,
          "ledreceiveqty": 0,
          "ledbalqty": 0,
          "bikestandqty": 0,
          "bikestandreceiveqty": 0,
          "bikestandbalqty": 0,
          "updateModuleName": "",
          "volumatricWeight": 0,
          "newSTaxRuleOn08Oct2015": true,
          "idProofName": "",
          "idProofNo": "",
          "isNewSTaxRuleOn15Nov2015": true,
          "treatMent": "",
          "isFromPRQ": true,
          "miscOriginCarpenter": true,
          "miscOriginPlumber": true,
          "miscOriginElectrician": true,
          "tarpetAlmerahQty": 0,
          "fridgeQTY": 0,
          "washingMachineQTY": 0,
          "isFromTab": true,
          "invAmt1": 0,
          "invAmt2": 0,
          "isfoV_6Feb2016": true,
          "iS100KMRULE": true,
          "serialNo": "",
          "skuid": "",
          "chkDDL": true,
          "totalKM": 0,
          "csgeFloor": 0,
          "entryType": "",
         "isVolumetric": this.docketService.step2DetailsList.isVolumentric ==='Y'?true:false,
         "isCODDOD": this.docketService.step2DetailsList.isCODDOD ==='Y'?true:false,
          "isODA": this.docketService.step2DetailsList.IsODA ==='Y'?true:false,
         "isDACC":this.docketService.step2DetailsList.isDACC ==='Y'?true:false,
          "isLocalDocket": this.docketService.basicDetailForm.value.IsLocalDocket?true:false,
           "isStaxExemp": this.docketService.basicDetailForm.value.exemptServices === 'Y'?true:false,
          // "appointmentDT":  this.docketService.basicDetailForm.value.appointmentDT ? 
          // new Date(this.docketService.basicDetailForm.value.appointmentDT).toISOString()
          // : null,
            // "appointmentDT": new Date(this.docketService.basicDetailForm.value.appointmentDT).toISOString(),
          "person": this.docketService.basicDetailForm.value.personName,
          "apmtMobile": this.docketService.basicDetailForm.value.contactNo,
          "apmtRemark": this.docketService.basicDetailForm.value.remarks,
          "fromTime": this.docketService.basicDetailForm.value.fromTime,
          "toTime": this.docketService.basicDetailForm.value.toTime,
          "appointmentNo": "",
          "csdNo": "",
          "msdNo": "",
          "staxExceedLimit": 0,
          "cftWtRatio": this.docketService.invoiceform.value.cft_Ratio,
          "cfttot": this.docketService.invoiceform.value.cftTotal,
          "decval": this.docketService.invoiceform.value.totalDeclaredValue,
          "volMeasureType": "",
          "cftWeightType": "",
          "contractId": this.docketService.step2DetailsList.contractid,
          "chargeRule": "NONE",
          "chargeSubRule": "NONE",
          "baseCode1": "NONE",
          "baseCode2": "NONE",
          "contractDepth": this.docketService.depth,
          "flagProceed": this.docketService.flagprocedd,
          "minFreightType": "",
          "flaG_Freight": "",
          "flaG_Subtotal": "",
          "minFreightBas": "",
          "minFreightBasRate": 0,
          "subTotalUpperLimit": 0,
          "subTotalLowerLimit": 0,
          "minSubtotal": 0,
          "freightRateUpperLimit": 0,
          "freightRateLowerLimit": 0,
          "minFreightRate": 0,
          "fuelRateType": "",
          "fuelRate": 0,
          "minFuleCharge": 0,
          "maxFuelCharge": 0,
          "codRateType": this.docketService.step2DetailsList.codRateType,
          "min_CODCharged": this.docketService.step2DetailsList.min_CODCharged,
          "codCharged": this.docketService.step2DetailsList.codCharged,
          "daccRateType": this.docketService.step2DetailsList.daccRateType,
          "daccCharged": this.docketService.step2DetailsList.daccCharged,
          "min_DACCCharged": this.docketService.step2DetailsList.min_DACCCharged,
          "dktdaccCharges": 0,
          "dktdaccAmount": 0,
          "trDays": 0,
          "flagStaxBifer": "",
          "flagRoundOff": "",
          "flaG_PRORATA": "",
          "flagvolumetric": "",
          "flagcoddod": "",
          "flagoda": "",
          "flaglocal": "",
          "flagdacc": "",
          "ftltype": this.docketService.basicDetailForm.value.typeMovement,
          "dockdate": this.docketService.basicDetailForm.value.cNoteDate,
          "arriveddate": "",
          "isCheck": true,
          "reasonCode": "",
          "id": 0,
          "edD_Date": "",
          // "sdD_Date": new Date().toISOString(),
          // "sdD_Date": '2025-08-18T05:45:05.992Z',

          "kM_From_Location": 0,
          "is_ODA_Apply": this.docketService.basicDetailForm.value.isODAApplicable,
          "cod": 0,
          "dacc": 0,
          "mailId": "",
          "odaFlag": "",
          "is_EDDDays_Apply": "",
          "ticketNo": "",
          "referenceNo": this.docketService.basicDetailForm.value.referenceDocket,
          "mailId1": "",
          "mailId2": "",
          "coD_DOC_Cancel": "",
          "dacC_Cancel": "",
          "originStateCode": this.docketService.basicDetailForm.value.csgngstState,
          "originStateName": this.docketService.basicDetailForm.value.originState,
          "isOriginUnionTerritory": true,
          "destStateCode": this.docketService.basicDetailForm.value.csgegstState,
          "destStateName": this.docketService.basicDetailForm.value.destinationState,
          "isDestUnionTerritory": true,
          "isUnionTeritory": true,
          "origin_Area": this.docketService.basicDetailForm.value.originState,///consinee mathi avshe adress
          "destination_Area": this.docketService.basicDetailForm.value.destinationState,///consinor mathi avshe adress
          "custGSTNo": "",
          "custGSTState": "",
          "csgeCustGSTNo": this.docketService.consignorForm.value.consigneeGSTNo,
          "csgeCustGSTState": "string",
          "isCompletion": true,
          "billingState": this.docketService.freightForm.value.billingState,
          "orgN_DEST": "string",
          "isHOVerified": true,
          "eWayBillNo": this.docketService.basicDetailForm.value.ewayBillNo,
          "eWayBillExpiredDate": "",
          "eWayInvoicevalue": 0,
          "isCounterPickUpPRS": true,
          "isCounterDelivery": true,
          "retailsd": true,
          "ewayInvoiceVAL": "",
          "branchType": "",
          "prQ_Customer": "",
          "srno": 0,
          "isDockType": "DKT",
          "txtVehicleNo": this.docketService.basicDetailForm.value.vehicleno,
          "bcSerialNo": "",
          "isReferenceDKT": this.docketService.basicDetailForm.value.isreferenceDKT,
          "referenceDocketNo": this.docketService.basicDetailForm.value.referenceDocket,
          "totalPiece": 0,
          "isDKTPayment": this.docketService.basicDetailForm.value.isDocketPayment,
          "addableOtherChg": 0,
          "calculateOn": "",
          "goodsCategory": "",
          "bookingType": "",
          "ccAttached": true,
          "remarks": "",
          "loadingOrder": "",
          "totGoodsPkgs": 0,
          "totGoodsWeight": 0,
          "totGoodsFreight": 0,
          "lastDockNo": "",
          "gstRateType": this.docketService.freightForm.value.gstRate,
          "isLSDocket": true,
          "op_Status": "",
          "last_LOC": "",
          "lorrayType": "",
          "delyreason": "",
          "statusCode": "",
          "origin": this.docketService.basicDetailForm.value.origin,
          "destination": this.docketService.basicDetailForm.value.destination,
          "shortageRemarks": "",
          "consignor": this.docketService.consignorForm.value.consignorSelection,
          "consignee": this.docketService.consignorForm.value.consigneeSelection,
          "billingParty": this.docketService.basicDetailForm.value.billingParty,
          "freight": this.docketService.freightForm.value.freightCharge,
          "billigLocation": this.docketService.step2DetailsList.billingLocation,
          "docdt": this.docketService.basicDetailForm.value.cNoteDate,
          "qtyt": 0,
          "booking": "",
          "dly": "",
          "curr_Loc": "",
          "mrsno": "",
          "mrsdt": "",
          "mrsamt": 0,
          "billno": "",
          "bgndt": "",
          "billamt": 0,
          "fM_no": "",
          "fM_Date": "",
          "ackdt": "",
          "poD_location_Date": "",
          "podLink": "",
          "toLoc": "",
          "fM_Ack_By": "",
          "igstAmount": this.docketService.freightForm.value.igstamount,
          "igstRate": this.docketService.freightForm.value.igstrate,
          "subTotal": this.docketService.freightForm.value.subTotal,
          "dkttot": this.docketService.freightForm.value.dktTotal,  //total fright form nu
          "cgstRate": this.docketService.freightForm.value.cgstrate,//pucchvanau
          "cgstAmount": this.docketService.freightForm.value.cgstamount,//pucchvanau
          "sgstRate": this.docketService.freightForm.value.sgstrate,//pucchvanau
          "sgstAmount": this.docketService.freightForm.value.sgstamount,//pucchvanau
          "utgstRate": this.docketService.freightForm.value.utgstrate,//pucchvanau
          "utgstAmount": this.docketService.freightForm.value.utgstamount,//pucchvanau
          "grossValue": 0,
          "rate_Type": this.docketService.freightForm.value.rateType,
          "freight_Rate": this.docketService.freightForm.value.freightRate,
          "piece": 0,
          "pieceAMT": 0,
          "tpCustGSTNo": "",
          "tpcd": "",
          "tpnm": "",
          "tpaddr": "",
          "tpCity": "",
          "tpPinCode": "",
          "tpTeleNo": "",
          "codeDesc": "",
          "codeId": "",
          "docketNo": this.docketService.basicDetailForm.value.cNoteNo,
          "tranXaction": "",
          "isCSGEFloorVisible": "",
          "isPaymentDetailsVisible": "",
          "url": "",
          "sacCode": this.docketService.basicDetailForm.value.sacCode,
          "sacCodeDesc": this.docketService.basicDetailForm.value.sacDescription,
          "eWayBillAPIEnable": true,
          "exemptServices": this.docketService.basicDetailForm.value.exemptServices,
          "gstDeclaration": "",
          "gstRate": this.docketService.basicDetailForm.value.gstRate,
          "gstDeclarationDoc": "",
          "declarationType": "",
          "custcat": "",
          "custcatDesc": "",
          "consigneeCUSTCAT": "",
          "consigneeCUSTCATDesc": "",
          "image": "",
          "isFromBillGeneration": "",
          "gtaSacCode": this.docketService.basicDetailForm.value.sacCode,
          "gtaSacCodeDesc": this.docketService.basicDetailForm.value.sacDescription,
          "vehicleType": this.docketService.basicDetailForm.value.vehicleType,
          "thirdParty": "",
          "isAppointmentDelivery": this.docketService.basicDetailForm.value.isAppointmentDelivery,
          "isCSDDelivery": this.docketService.basicDetailForm.value.iscsdDelivery,
          "isMAllDelivery": this.docketService.basicDetailForm.value.IsMAllDeliveryN,
          "discount": this.docketService.freightForm.value.discount,
          "isOnSubtotalorTotal": "",
          "pincode": this.docketService.basicDetailForm.value.pincode,
          "subreasoncode": "",
          "outstandingAmount": 0,
          "grpcd": "",
          "discountAmount": this.docketService.freightForm.value.discountAmount,
          "indentNo": "",
          "srNumber": 0,
          "fromDate": "",
          "toDate": "",
          "fuelRateType_Ftl": "",
          "fuelRate_Ftl": 0,
          "minFuleCharge_Ftl": 0,
          "maxFuelCharge_Ftl": 0
        },
        "oldPayBas": this.docketService.basicDetailForm.value.billingParty,
        "olddkttot": 0,
      // },
      wmdc: {
        "dockno": this.docketService.basicDetailForm.value.cNoteNo,
        "ratE_TYPE": Number(this.docketService.freightForm.value.rateType)||0,
        "frT_RATE": Number(this.docketService.freightForm.value.freightRate)||0,
        "freighT_CALC": Number(this.docketService.freightForm.value.freightCharges)||0,
        "freight": Number(this.docketService.freightForm.value.freightCharges)||0,
        "fov": this.docketService.freightForm.value.fovRate,
        "schG01": this.docketService.freightForm.value.SCHG01,
        "schG02": this.docketService.freightForm.value.SCHG02,
        "schG03": this.docketService.freightForm.value.SCHG03,
        "schG04": this.docketService.freightForm.value.SCHG04,
        "schG05": this.docketService.freightForm.value.SCHG05,
        "schG06": this.docketService.freightForm.value.SCHG06,
        "schG07": this.docketService.freightForm.value.SCHG07,
        "schG08": this.docketService.freightForm.value.SCHG08,
        "schG09": this.docketService.freightForm.value.SCHG09,
        "schG10": this.docketService.freightForm.value.SCHG10,
        "schG11": this.docketService.freightForm.value.SCHG11,
        "schG12": this.docketService.freightForm.value.SCHG12,
        "schG13": this.docketService.freightForm.value.SCHG13,
        "schG14": this.docketService.freightForm.value.SCHG14,
        "schG15": this.docketService.freightForm.value.SCHG15,
        "schG16": this.docketService.freightForm.value.SCHG16,
        "schG17": this.docketService.freightForm.value.SCHG17,
        "schG18": this.docketService.freightForm.value.SCHG18,
        "schG19": this.docketService.freightForm.value.SCHG19,
        "schG20": this.docketService.freightForm.value.SCHG20,
        "schG21": this.docketService.freightForm.value.SCHG21,
        "schG22": this.docketService.freightForm.value.SCHG22,
        "schG23": this.docketService.freightForm.value.SCHG23,
        "uchG01": this.docketService.freightForm.value.UCHG01,
        "uchG02": this.docketService.freightForm.value.UCHG02,
        "uchG03": this.docketService.freightForm.value.UCHG03,
        "uchG04": this.docketService.freightForm.value.UCHG04,
        "uchG05": this.docketService.freightForm.value.UCHG05,
        "uchG06": this.docketService.freightForm.value.UCHG06,
        "uchG07": this.docketService.freightForm.value.UCHG07,
        "uchG08": this.docketService.freightForm.value.UCHG08,
        "uchG09": this.docketService.freightForm.value.UCHG09,
        "uchG10": this.docketService.freightForm.value.UCHG10,
        "subTotal": this.docketService.freightForm.value.subTotal,
        "svctax": 0,
        "cess": 0,
        "dkttot": 0,
        "hedu_cess": 0,
        "p01Amount": 0,
        "p03Amount": 0,
        "svctaX_Rate": 0,
        "balanceAmount": 0,
        "lasteditdate": "",
        "comments": "",
        "savedby": "",
        "savingdate": "",
        "editModule": "",
        "discount": Number(this.docketService.freightForm.value.discount)||0,
        "surChgExcludefrom27dec14": true,
        "isAdditionalAmountAdd": true,
        "addtionalCharge": 0,
        "lessCharge": 0,
        "fovRate": this.docketService.freightForm.value.fovRate,
        "surChargeRate": 0,
        "cfrwaybillno": "",
        "cfrwaybillamt": 0,
        "cfrtotalwaybillamt": 0,
        "cfrwaybillSeriviceTax": 0,
        "tollTaxPer": 0,
        "tollTaxCharge": 0,
        "otherServiceTaxPer": 0,
        "otherServiceTaxAmt": 0,
        "otherServiceSubTotal": 0,
        "transportationTotalAmt": 0,
        "otherServiceTotalAmt": 0,
        "otherServiceDiscount": 0,
        "transportationDiscount": 0,
        "writeOffComment": "",
        "extraGoodsValue": 0,
        "extraFovAmt": 0,
        "extraFovPer": 0,
        "isServiceTaxExempted": true,
        "isSurChargesExempted": true,
        "manualInvoiceNo": "",
        "manualInvoiceDate": "",
        "isFromPRQ": true,
        "rate": "",
        "volume": "",
        "wayBillDate": "",
        "isFromTab": true,
        "fovRate2": 0,
        "sbcRate": 0,
        "sbCess": 0,
        "fovCalculated": 0,
        "kkcRate": 0,
        "kkcAmount": 0,
        "greenTax": 0,
        "stax_paidby": "",
        "gstType": this.docketService.gstCalculationList.gstType,
        "isGSTApplied": true,
        "igstRate": this.docketService.freightForm.value.igstrate,
        "igstAmount": this.docketService.freightForm.value.igstrate,
        "cgstRate": this.docketService.freightForm.value.cgstrate,
        "cgstAmount": this.docketService.freightForm.value.cgstamount,
        "sgstRate": this.docketService.freightForm.value.sgstrate,
        "sgstAmount": this.docketService.freightForm.value.sgstamount,
        "utgstRate": this.docketService.freightForm.value.utgstrate,
        "utgstAmount": this.docketService.freightForm.value.utgstamount,
        "advanceAmount": 0,
        "discountValue": 0,
        "schG24": this.docketService.freightForm.value.SCHG23,
        "schG25": this.docketService.freightForm.value.SCHG25,
        "schG26": this.docketService.freightForm.value.SCHG26,
        "schG27": this.docketService.freightForm.value.SCHG27,
        "schG28": this.docketService.freightForm.value.SCHG28,
        "schG29": this.docketService.freightForm.value.SCHG29,
        "schG30": this.docketService.freightForm.value.SCHG30,
        "uchG11": this.docketService.freightForm.value.UCHG11,
        "uchG12": this.docketService.freightForm.value.UCHG12,
        "uchG13": this.docketService.freightForm.value.UCHG13,
        "uchG14": this.docketService.freightForm.value.UCHG14
      },
      "listInVoice": invoiceList,
      "listCharges": listCCH,
      "listDocument": [
        {
          "dockno": this.docketService.basicDetailForm.value.cNoteNo,
          "comments": "",
          "docksf": "",
          "srno": 0,
          "documentno": ""
        }
      ],
      "delivered": "",
      "prsdone": "",
      "drsdone": "",
      "objPRQ": {
        "id": 0,
        "prqNo": "",
        "preferdAddress": "",
        "address": "",
        "landMark": "",
        "city": "",
        "pincode": "",
        "state": "",
        "name": "",
        "mobileNo": "",
        "vehicleType": "",
        "approxWeight": 0,
        "pkgs": 0,
        "imeiNo": "",
        "originLat": "",
        "originLong": "",
        "brcd": "",
        "changeBRCD": "",
        "status": 0,
        "remarks": "",
        "vehicleNo": "",
        "driverID": "",
        "driverName": "",
        "isAssign": true,
        "assignBy": "",
        "assignTo": "",
        "assignDate": "",
        "isReject": true,
        "rejectBy": "",
        "rejectDate": "",
        "isCancel": true,
        "cancelBy": "",
        "cancelDate": "",
        "entryBy": "",
        "entryDate": "",
        "isFromAndroid": true,
        "excepctedEndDate": "",
        "excepctedEndDateStr": "",
        "type_Name": "",
        "selectedGoogleAddress": "",
        "actualWeight": 0,
        "actualPKGS": 0,
        "customerName": "",
        "customerCode": "",
        "custName": "",
        "prqDate": "",
        "dockNo": "",
        "destcd": "",
        "isDocketCompleted": true,
        "docketGeneratedDate": "",
        "docketGenerateBy": "",
        "docketCompletedBy": "",
        "docketCompletedDate": "",
        "isDocketGenerated": true,
        "from_Area": "",
        "to_Area": "",
        "finYear": "",
        "consignorAddress": "",
        "consigneeName": "",
        "consignorName": "",
        "size_Width": 0,
        "size_Length": 0,
        "size_Heigth": 0,
        "prqcategory": "",
        "eWayBillNo": "",
        "priorityType": "",
        "planReceivedDateTime": "",
        "requiredPlacementDateTime": "",
        "fromCity": "",
        "toCity": "",
        "fromLocation": "",
        "toLocation": "",
        "invoiceNo": "",
        "businessType": "",
        "truckType": "",
        "approximateWeight": 0,
        "noOfPkgs": 0,
        "expectedrate": 0,
        "loadingCharges": 0,
        "loadingSlots": "",
        "unloadingCharges": 0,
        "unloadingSlots": "",
        "loading_Point": "",
        "unLoading_Point": "",
        "prQ_Id": 0,
        "priorityTypeDisp": "",
        "planReceivedDateTimeDisp": "",
        "requiredPlacementDateTimeDisp": "",
        "businessTypeDisp": "",
        "truckTypeDisp": "",
        "entrydateDisp": "",
        "prqStatus": "",
        "planeStatus": "",
        "srNo": 0,
        "isCheck": true,
        "ageing": 0,
        "etA_Time": "",
        "etA_TimeDisp": "",
        "remark": "",
        "typ": "",
        "vehicleStatus": "",
        "prqStatus1": "",
        "isFreeze": true,
        "load_UnloadSrNo": ""
      },
      "isCompletion": false,
      "docketType": "DKT",
      "isFromCompletion": "",
      "dqgcc": {
        "rid": 0,
        "docketNo": "",
        "fromDate": "",
        "toDate": "",
        "custCode": "",
        "custName": "",
        "origin": ""
      },
      "dqgcclst": [
        {
          "rid": 0,
          "docketNo": "",
          "fromDate": "",
          "toDate": "",
          "custCode": "",
          "custName": "",
          "origin": ""
        }
      ],
      // },
      "docketInvoiceList": [
        {
          "srNo": 0,
          "dockno": "",
          "invno": "",
          "invdt": "",
          "declval": 0,
          "pkgsno": 0,
          "actuwt": this.docketService.invoiceform.value.actualWeight,
          "voL_L": 0,
          "voL_B": 0,
          "voL_H": 0,
          "toT_CFT": 0,
          "vol_cft": 0,
          "part_No": "",
          "eWayBillNo": "",
          "eWayBillExpiredDate": "",
          "eWayInvoicevalue": 0,
          "eWayBillInvoiceDate": "",
          "hsnCode": "",
          "qty": 0,
          "itemCode": "",
          "transportrate": 0,
          "piece": 0,
          "pieceAmount": 0,
          "pieceWeight": 0,
          "volumetricBox": "",
          "pieceRateType": "",
          "chrgwt": 0
        }
      ],
      "docketChargesList": listCCH,
      "listBarCode": [
        {
          "dockNo": this.docketService.basicDetailForm.value.cNoteNo,
          "bcFrom": "",
          "bcTo": ""
        }
      ],
      "doctyp": "DKT",
      "dynamicList": listCCH,
      "PC": {
        "paymentMode": "",
        "payAmount": 0,
        "cashAmount": 0,
        "cashLedger": "",
        "chequeAmount": 0,
        "bankLedger": "",
        "chequeNo": "",
        "cashLedgerName": "",
        "bankLedgerName": "",
        // "chequeDate":new Date().toISOString(),
        // "chequeDate":'2025-08-18T05:45:05.992Z',
        "chequeAmount_Fromcheque": "",
        "tdsType": "",
        "isDepositedInBank": true,
        "depositedInBank": "",
        "received_From_Bank": "",
        "bank_Branch": "",
        "isOnAccount": true,
        "neT_RECEIVED": 0,
        "collection_Amt_From_Cheque": 0,
        "acccode": "",
        "isFuelCard": true,
        "fuelCardNo": "",
        "vehicleNo": "",
        "isTDSApplicable": true,
        "tanNo": "",
        "tdsPercentage": 0,
        "totTDSAmt": 0,
        "moduleType": "",
        "isAllowForChequeCollection": true,
        "isHappayCard": true,
        "happyCardNo": "",
        "happyLedger": "",
        "remarks": "",
        "isATMCard": true,
        "atmCardNo": ""
      },
      "gstDeclaration": [
        null
      ]
    };

   
    const listDocument = [
      {
        "dockno": this.docketService.basicDetailForm.value.cNoteNo,
        "comments": "",
        "docksf": "",
        "srno": 0,
        "documentno": ""
      }
    ]

    const listBarCode = [
      {
        "dockNo": this.docketService.basicDetailForm.value.cNoteNo,
        "bcFrom": "",
        "bcTo": ""
      }
    ]

    const docketInvoiceList = [
      {
        // "srNo": 0,
        "dockno": "",
        "invno": "",
        "invdt": "",
        "declval": 0,
        "pkgsno": 0,
        "actuwt": this.docketService.invoiceform.value.actualWeight,
        "voL_L": 0,
        "voL_B": 0,
        "voL_H": 0,
        // "toT_CFT": 0,
        "vol_cft": 0,
        "part_No": "",
        "eWayBillNo": "",
        "eWayBillExpiredDate": "",
        "eWayInvoicevalue": 0,
        "eWayBillInvoiceDate": "",
        "hsnCode": "",
        "qty": 0,
        "itemCode": "",
        "transportrate": 0,
        "piece": 0,
        "pieceAmount": 0,
        "pieceWeight": 0,
        // "volumetricBox": "",
        "pieceRateType": "",
        "chrgwt": 0
      }
    ]

    const dqgcclst = [
      {
        "rid": 0,
        "docketNo": "",
        "fromDate": "",
        "toDate": "",
        "custCode": "",
        "custName": "",
        "origin": ""
      }
    ]

    console.log(payload)
    const formData = new FormData();
    // formData.append("PC", JSON.stringify(PC));
    // formData.append("dynamicList", JSON.stringify(listCCH));
    // formData.append("listCharges", JSON.stringify(listCCH));
    // formData.append("listDocument", JSON.stringify(listDocument));
    // formData.append("gstDeclaration", JSON.stringify(gstDeclaration));
    // formData.append("objPRQ",JSON.stringify(objPRQ));

    formData.append("listCCH", JSON.stringify(listCCH));
    formData.append("listInVoice", JSON.stringify(invoiceList));
    formData.append("listCharges", JSON.stringify(listCCH));
    formData.append("listDocument", JSON.stringify(listDocument));
    formData.append("dqgcclst", JSON.stringify(dqgcclst));
    formData.append("docketInvoiceList", JSON.stringify(docketInvoiceList));
    formData.append("docketChargesList", JSON.stringify(listCCH));
    formData.append("listDocument", JSON.stringify(listDocument));
    formData.append("listBarCode", JSON.stringify(listBarCode));
    formData.append("DynamicList", JSON.stringify(listCCH));
    this.appendObjectToFormData(formData, payload.wmd, "DVM.WMD");
    formData.append("DVM.OLDPayBas", this.docketService.basicDetailForm.value.billingParty)
    formData.append("DVM.OLDPayBas", "0");
    formData.append("DVM.WMD.insupldt",new Date(this.docketService.consignorForm.value.policyDate).toISOString()),
     formData.append("DVM.PC.chequeDate",new Date().toISOString()),
     formData.append("DVM.WMD.permitdt",new Date().toISOString()),
     formData.append("DVM.WMD.sdD_Date",new Date().toISOString()),
   formData.append("DVM.WMD.dockdt",this.docketService.basicDetailForm.value.cNoteDate? new Date(this.docketService.basicDetailForm.value.cNoteDate).toISOString(): '');
formData.append( "DVM.WMD.cdeldt", new Date(this.docketService.freightData.edd).toISOString()),

    formData.append("DVM.WMD.AppointmentDT",new Date(this.docketService.basicDetailForm.value.appointmentDT).toISOString()),

    this.appendObjectToFormData(formData, payload.wmdc, "DVM.WMDC");
    formData.append("DVM.Delivered", "");
    formData.append("DVM.PRSDONE", "");
    formData.append("DVM.DRSDONE", "");
    this.appendObjectToFormData(formData, payload.objPRQ, "DVM.OBJPRQ");
    formData.append("DVM.isCompletion", "false")
    formData.append("DVM.docketType", "DKT");
    formData.append("DVM.IsFromCompletion", "");
    this.appendObjectToFormData(formData, payload.dqgcc, "DQGCC");
    formData.append("DOCTYP", "DKT");
    this.appendObjectToFormData(formData, payload.PC, "PC");
    formData.append("GSTDeclaration", "");
    formData.append("BaseFinYear", "2025-2026");
    formData.append("BaseCompanyCode", "C003");
    formData.append("BaseUserName", this.docketService.BaseUserCode);
    console.log(formData)

    this.basicDetailService.onSubmit(formData).subscribe({
      next: (response: any) => {
        if (response) {
          Swal.fire({
            icon: 'success',
            title: 'Saved!',
            text: 'Docket saved successfully.',
            timer: 2000,
            showConfirmButton: false
          });
        }
      }
    });
  }

  appendObjectToFormData(formData: FormData, obj: any, parentKey: string = "") {
    for (const key in obj) {
      if (obj.hasOwnProperty(key)) {
        const value = obj[key];
        const formKey = parentKey ? `${parentKey}.${key}` : key;

        if (value !== null && typeof value === "object" && !Array.isArray(value)) {
          // Recursive call if nested object
          this.appendObjectToFormData(formData, value, formKey);
        } else {
          formData.append(formKey, JSON.stringify(value ?? ""));
        }
      }
    }
  }

}

