import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Output, TemplateRef, ViewChild } from '@angular/core';
import { BsModalRef, BsModalService } from 'ngx-bootstrap/modal';
import { PRSDRSApiService } from 'app/shared/services/prsdrs-api.service';
import { DocketService } from 'app/shared/services/docket.service';

@Component({
  selector: 'app-deps-details',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './deps-details.component.html',
  styleUrl: './deps-details.component.scss'
})
export class DepsDetailsComponent {
  public modalRef!: BsModalRef;
  public drsNo: string = '';
  public depsNo: string = '';
  public dateStr: string = '';
  public vendorName: string = '';
  public totalDeliveredDockets: number = 0;
  public generatedBy: string = '';
  public totalExceptions: number = 0;
  public depsList: any[] = [];
  public isLoading: boolean = false;

  @Output() dataEmitter = new EventEmitter<void>();
  @ViewChild('TemplateDepsDetails', { static: true }) TemplateDepsDetails!: TemplateRef<any>;

  constructor(
    private modalService: BsModalService,
    private prsdrsApiService: PRSDRSApiService,
    private docketService: DocketService
  ) {}

  showPopup(data: any) {
    this.drsNo = data.drsNo || 'DS/MUM/2526/0000302';
    this.depsNo = data.depsNo || '5 DEPS IDs';
    this.vendorName = data.vendorName || 'Admin / MUM';
    this.totalDeliveredDockets = data.deliveredCount || data.totalDockets || 0;
    
    // Parse Date format
    this.dateStr = data.drsDate || '2026-06-17T16:06:00';

    // Generated By details: use logged in user information or data-provided user
    const username = this.docketService.loginUserList?.BaseUserName || 'Admin';
    const location = this.docketService.loginUserList?.LocationCode || 'MUM';
    this.generatedBy = `${username} / ${location}`;

    this.isLoading = false;
    
    // Set static mockup exception records matching the design
    this.depsList = [
      {
        depsNo: 'DE/MUM/2026/000011',
        dockno: 'DKT/2526/20101',
        dockdt: '21-Mar-26',
        orgncd: 'MUM',
        destcd: 'DEL',
        pkgsno: 4,
        depstype: 'S',
        affectedPkgs: 2,
        damageType: '—',
        severity: '—',
        remarks: 'sf',
        fileAttached: true,
        fileName: '62920329.png',
        fileUrl: '#'
      },
      {
        depsNo: 'DE/MUM/2026/000012',
        dockno: 'DKT/2526/20102',
        dockdt: '21-Mar-26',
        orgncd: 'MUM',
        destcd: 'BLR',
        pkgsno: 6,
        depstype: 'S',
        affectedPkgs: 2,
        damageType: '—',
        severity: '—',
        remarks: 'dsf',
        fileAttached: true,
        fileName: '81128307.png',
        fileUrl: '#'
      },
      {
        depsNo: 'DE/MUM/2026/000013',
        dockno: 'DKT/2526/20103',
        dockdt: '21-Mar-26',
        orgncd: 'MUM',
        destcd: 'HYD',
        pkgsno: 3,
        depstype: 'S',
        affectedPkgs: 1,
        damageType: '—',
        severity: '—',
        remarks: 'dsf',
        fileAttached: true,
        fileName: '81128307.png',
        fileUrl: '#'
      },
      {
        depsNo: 'DE/MUM/2026/000014',
        dockno: 'DKT/2526/20104',
        dockdt: '21-Mar-26',
        orgncd: 'MUM',
        destcd: 'CHN',
        pkgsno: 5,
        depstype: 'S',
        affectedPkgs: 2,
        damageType: '—',
        severity: '—',
        remarks: 'sdf',
        fileAttached: true,
        fileName: '62920329.png',
        fileUrl: '#'
      },
      {
        depsNo: 'DE/MUM/2026/000015',
        dockno: 'DKT/2526/20105',
        dockdt: '21-Mar-26',
        orgncd: 'MUM',
        destcd: 'PUN',
        pkgsno: 2,
        depstype: 'S',
        affectedPkgs: 1,
        damageType: '—',
        severity: '—',
        remarks: 'sdf',
        fileAttached: true,
        fileName: '81128307.png',
        fileUrl: '#'
      }
    ];

    this.totalExceptions = this.depsList.length;

    this.modalRef = this.modalService.show(this.TemplateDepsDetails, {
      class: 'modal-xxl modal-dialog-centered deps-details-modal-wrapper',
      backdrop: 'static'
    });
  }

  getDepsTypeLabel(type: string): string {
    if (type === 'D') {
      return 'Damage';
    } else if (type === 'S') {
      return 'Shortage';
    }
    return type || '—';
  }

  getDepsTypeClass(type: string): string {
    if (type === 'D') return 'badge-damage';
    if (type === 'S') return 'badge-shortage';
    return 'badge-secondary';
  }

  closePopup() {
    if (this.modalRef) {
      this.modalRef.hide();
    }
  }

  printDetails() {
    // Inject dynamic style tag to override page margin globally (removes browser header/footer)
    const style = document.createElement('style');
    style.id = 'deps-print-page-margins';
    style.innerHTML = '@page { margin: 0 !important; }';
    document.head.appendChild(style);

    document.documentElement.classList.add('deps-printing-mode');
    document.body.classList.add('deps-printing-mode');
    
    const afterPrint = () => {
      document.documentElement.classList.remove('deps-printing-mode');
      document.body.classList.remove('deps-printing-mode');
      
      const styleEl = document.getElementById('deps-print-page-margins');
      if (styleEl) {
        styleEl.remove();
      }
      
      window.removeEventListener('afterprint', afterPrint);
    };
    
    window.addEventListener('afterprint', afterPrint);
    setTimeout(() => {
      window.print();
    }, 50);
  }
}
